# Generated by Django 5.1.2 on 2024-11-25 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralproducer',
            name='crops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brainweb.crop', verbose_name='Culturas'),
        ),
    ]
