# Generated by Django 5.1.2 on 2024-11-26 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0003_remove_ruralproducer_crops_crop_ruralproducer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='ruralProducer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='brainweb.ruralproducer', verbose_name='Culturas'),
        ),
    ]
