# Generated by Django 5.1.2 on 2024-11-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0004_alter_crop_ruralproducer'),
    ]

    operations = [
    ]
