# Generated by Django 5.1.2 on 2024-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0006_remove_crop_ruralproducer_crop_ruralproducers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='ruralProducers',
            field=models.ManyToManyField(to='brainweb.ruralproducer', verbose_name='Produtores'),
        ),
    ]
