# Generated by Django 5.1.2 on 2024-11-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0007_alter_crop_ruralproducers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='ruralProducers',
        ),
        migrations.AddField(
            model_name='ruralproducer',
            name='crops',
            field=models.ManyToManyField(to='brainweb.crop', verbose_name='Culturas'),
        ),
    ]
